### ISSUE TITLE
Trying to build for F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [standardnotes/mobile#292]
In metadata I've added the `yarn` line since it was complaining:
```
  - versionName: 3.0.22
    versionCode: 3000221
    commit: 3.0.22
    subdir: android/app/
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y --no-install-recommends -t stretch-backports npm
      - npm -g install yarn
    init: npm install
    gradle:
      - yes
    rm:
      - vendor/react-native-aes/android/build/
    prebuild:
      - truncate -s 0 ../../node_modules/@react-native-community/cli/build/commands/server/external/xsel
      - sed -i -e 's/gradle-4.1/gradle-5.4.1/' gradle/wrapper/gradle-wrapper.properties
    scanignore:
      - android/build.gradle
      - node_modules/react-native-screens/android/build.gradle
      - node_modules/react-native-webview/android/build.gradle
    scandelete:
      - node_modules/
      - vendor/
```

But what else am I missing?
```
+ npm -g install yarn

> yarn@1.22.10 preinstall /usr/local/lib/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.10
added 1 package in 3.008s
2020-10-05 10:18:46,471 INFO: Getting source for revision 3.0.22
2020-10-05 10:18:46,472 DEBUG: Directory: build/com.standardnotes
2020-10-05 10:18:46,472 DEBUG: > git rev-parse --show-toplevel
2020-10-05 10:18:46,678 DEBUG: Directory: build/com.standardnotes
2020-10-05 10:18:46,679 DEBUG: > git submodule foreach --recursive git reset --hard
2020-10-05 10:18:46,889 DEBUG: Directory: build/com.standardnotes
2020-10-05 10:18:46,889 DEBUG: > git submodule foreach --recursive git clean -dffx
2020-10-05 10:18:46,997 DEBUG: Directory: build/com.standardnotes
2020-10-05 10:18:46,997 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bit
bucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.instea
dOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=
git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com fetch origin
2020-10-05 10:18:47,609 DEBUG: Directory: build/com.standardnotes
2020-10-05 10:18:47,610 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bit
bucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.instea
dOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=
git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com fetch --prune --tags --force origin
2020-10-05 10:18:48,231 DEBUG: Directory: build/com.standardnotes
2020-10-05 10:18:48,232 DEBUG: > git remote set-head origin --auto
2020-10-05 10:18:48,953 DEBUG: Directory: build/com.standardnotes
2020-10-05 10:18:48,953 DEBUG: > git checkout -f 3.0.22
2020-10-05 10:18:49,187 DEBUG: Directory: build/com.standardnotes
2020-10-05 10:18:49,188 DEBUG: > git clean -dffx
2020-10-05 10:18:49,297 INFO: Running 'init' commands in build/com.standardnotes/android/app/
2020-10-05 10:18:49,299 DEBUG: Directory: build/com.standardnotes/android/app
2020-10-05 10:18:49,299 DEBUG: > bash -x -c -- npm install
+ npm install
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > core-js@2.6.11 postinstall /home/vagrant/.npm/_cacache/tmp/git-clone-79c55765/node_modules/core-js
npm ERR! prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[96mThank you for using core-js (ESC[94m https://github.com/zloirock/core-js ESC[96m) for polyfilling JavaScript standard library!ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: ESC[0m
npm ERR! prepareGitDep ESC[96m>ESC[94m https://opencollective.com/core-js ESC[0m
npm ERR! prepareGitDep ESC[96m>ESC[94m https://www.patreon.com/zloirock ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[96mAlso, the author of core-js (ESC[94m https://github.com/zloirock ESC[96m) is looking for a good job -)ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > react-native-webview@8.0.1 prepare /home/vagrant/.npm/_cacache/tmp/git-clone-79c55765
npm ERR! prepareGitDep > yarn build
npm ERR! prepareGitDep
npm ERR! prepareGitDep yarn run v1.22.10
npm ERR! prepareGitDep $ yarn tsc
npm ERR! prepareGitDep $ /home/vagrant/.npm/_cacache/tmp/git-clone-79c55765/node_modules/.bin/tsc

npm ERR! prepareGitDep ESC[96mnode_modules/jest-diff/build/diffLines.d.tsESC[0m:ESC[93m8ESC[0m:ESC[93m34ESC[0m - ESC[91merrorESC[0mESC[90m TS1005: ESC[0m';' expected.
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[7m8ESC[0m import type { DiffOptions } from './types';
npm ERR! prepareGitDep ESC[7m ESC[0m ESC[91m                                 ~~~~~~~~~ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[96mnode_modules/jest-diff/build/index.d.tsESC[0m:ESC[93m10ESC[0m:ESC[93m13ESC[0m - ESC[91merrorESC[0mESC[90m TS1005: ESC[0m'=' expected.
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[7m10ESC[0m import type { DiffOptions } from './types';
npm ERR! prepareGitDep ESC[7m  ESC[0m ESC[91m            ~ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[96mnode_modules/jest-diff/build/index.d.tsESC[0m:ESC[93m10ESC[0m:ESC[93m34ESC[0m - ESC[91merrorESC[0mESC[90m TS1005: ESC[0m';' expected.
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[7m10ESC[0m import type { DiffOptions } from './types';
npm ERR! prepareGitDep ESC[7m  ESC[0m ESC[91m                                 ~~~~~~~~~ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[96mnode_modules/jest-diff/build/index.d.tsESC[0m:ESC[93m11ESC[0m:ESC[93m1ESC[0m - ESC[91merrorESC[0mESC[90m TS1128: ESC[0mDeclaration or statement expected.
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[7m11ESC[0m export type { DiffOptions, DiffOptionsColor } from './types';
npm ERR! prepareGitDep ESC[7m  ESC[0m ESC[91m~~~~~~ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[96mnode_modules/jest-diff/build/index.d.tsESC[0m:ESC[93m11ESC[0m:ESC[93m13ESC[0m - ESC[91merrorESC[0mESC[90m TS1005: ESC[0m';' expected.
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[7m11ESC[0m export type { DiffOptions, DiffOptionsColor } from './types';
npm ERR! prepareGitDep ESC[7m  ESC[0m ESC[91m            ~ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[96mnode_modules/jest-diff/build/index.d.tsESC[0m:ESC[93m11ESC[0m:ESC[93m52ESC[0m - ESC[91merrorESC[0mESC[90m TS1005: ESC[0m';' expected.
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[7m11ESC[0m export type { DiffOptions, DiffOptionsColor } from './types';
npm ERR! prepareGitDep ESC[7m  ESC[0m ESC[91m                                                   ~~~~~~~~~ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[96mnode_modules/jest-diff/build/printDiffs.d.tsESC[0m:ESC[93m8ESC[0m:ESC[93m13ESC[0m - ESC[91merrorESC[0mESC[90m TS1005: ESC[0m'=' expected.
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[7m8ESC[0m import type { DiffOptions, DiffOptionsNormalized } from './types';
npm ERR! prepareGitDep ESC[7m ESC[0m ESC[91m            ~ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[96mnode_modules/jest-diff/build/printDiffs.d.tsESC[0m:ESC[93m8ESC[0m:ESC[93m57ESC[0m - ESC[91merrorESC[0mESC[90m TS1005: ESC[0m';' expected.
npm ERR! prepareGitDep
npm ERR! prepareGitDep ESC[7m8ESC[0m import type { DiffOptions, DiffOptionsNormalized } from './types';
npm ERR! prepareGitDep ESC[7m ESC[0m ESC[91m                                                        ~~~~~~~~~ESC[0m
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep Found 9 errors.
npm ERR! prepareGitDep
npm ERR! prepareGitDep info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! prepareGitDep info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated @types/jest-diff@24.3.0: This is a stub types definition. jest-diff provides its own type definitions, so you do not need this installed.
npm ERR! prepareGitDep npm WARN notice [SECURITY] lodash has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=lodash&version=4.17.20 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! prepareGitDep npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! prepareGitDep npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep npm WARN notice [SECURITY] node-fetch has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=node-fetch&version=1.7.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! prepareGitDep npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! prepareGitDep npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! prepareGitDep npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! prepareGitDep npm WARN notice [SECURITY] yargs-parser has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=yargs-parser&version=11.1.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! prepareGitDep npm WARN notice [SECURITY] yargs-parser has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=yargs-parser&version=7.0.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! prepareGitDep npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! prepareGitDep npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN notice [SECURITY] set-value has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=set-value&version=2.0.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! prepareGitDep npm WARN notice [SECURITY] mem has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=mem&version=1.1.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! prepareGitDep error Command failed with exit code 2.
npm ERR! prepareGitDep error Command failed with exit code 2.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 2
npm ERR! prepareGitDep npm ERR! react-native-webview@8.0.1 prepare: `yarn build`
npm ERR! prepareGitDep npm ERR! Exit status 2
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the react-native-webview@8.0.1 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/vagrant/.npm/_logs/2020-10-05T10_21_13_150Z-debug.log
npm ERR! prepareGitDep
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: git+https://github.com/standardnotes/react-native-webview.git#92aac04e0f4e1e27edbce9e053436c6777a6f34a.
npm ERR! package.json npm can't find a package.json file in your current directory.
```

**Comment by radko93** [comment]
Hi, we are releasing a new version of the app soon that has a completely different build process. We can revisit this issue then. You can find code of the new app under `develop` branch.

**Comment by licaon-kter** [comment]
OK, new version, adapted recipe a bit:
```
  - versionName: 3.5.2
    versionCode: 3050200
    commit: 3.5.2
    subdir: android/app/
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y --no-install-recommends -t stretch-backports npm
      - sysctl fs.inotify.max_user_watches=524288
    init: npm install
    gradle:
      - prod
    rm:
      - .gitmodules
    prebuild:
      - $ANDROID_HOME/tools/bin/sdkmanager 'cmake;3.10.2.4988404'
      - sed -i -e '/splits\ {/,+7d' -e '/detox/d' -e '/DETOX_CI/d' build.gradle
    scanignore:
      - android/build.gradle
      - node_modules/hermes-engine
      - node_modules/jsc-android
      - node_modules/react-native/android
      - node_modules/react-native-aes-crypto/android/build.gradle
      - node_modules/react-native-keychain/android/build.gradle
      - node_modules/react-native-reanimated/android/build.gradle
      - node_modules/react-native-safe-area-context/android/build.gradle
      - node_modules/react-native-screens/android/build.gradle
      - node_modules/react-native-vector-icons/android/build.gradle
      - node_modules/react-native-webview/android/build.gradle
      - node_modules/sn-textview/android/build.gradle
      - node_modules/standard-notes-rn/android/build.gradle
      - node_modules/@bugsnag/react-native/android
      - node_modules/@bugsnag/react-native/bugsnag-react-native.gradle
      - node_modules/@react-native-community/async-storage/android/build.gradle
      - node_modules/@react-native-community/masked-view/android/build.gradle
    scandelete:
      - node_modules/
    ndk: r21d
```
But libsodium fails to build, what am I missing?

Fail log: 
[com.standardnotes_3050200.log.gz](https://github.com/standardnotes/mobile/files/5506566/com.standardnotes_3050200.log.gz)
